# Generated by Django 2.0.1 on 2018-03-09 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Behaviour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('type_behaviour', models.IntegerField(choices=[(1, 'And'), (0, 'Or')])),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=200)),
                ('behaviour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_behaviour', to='telegrambot.Behaviour')),
            ],
        ),
        migrations.CreateModel(
            name='Telegrambot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_trigger', models.CharField(max_length=100)),
                ('type_trigger', models.IntegerField(choices=[(0, 'Contains'), (1, 'Starts with'), (2, 'Ends with')])),
                ('behaviour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_behaviour', to='telegrambot.Behaviour')),
            ],
        ),
        migrations.AddField(
            model_name='behaviour',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_bot', to='telegrambot.Telegrambot'),
        ),
    ]
