# Generated by Django 2.0.1 on 2018-01-30 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behaviour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_trigger', models.IntegerField(choices=[(0, 'Starts with'), (1, 'Contains'), (2, 'Ends with')])),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Telegrambot',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_trigger', models.CharField(max_length=100)),
                ('command', models.BooleanField()),
                ('behaviour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_behaviour', to='telegrambot.Behaviour')),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_trigger', to='telegrambot.Trigger'),
        ),
        migrations.AddField(
            model_name='behaviour',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_bot', to='telegrambot.Telegrambot'),
        ),
    ]
