# Generated by Django 2.0 on 2017-12-24 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger', models.CharField(max_length=50)),
                ('response', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='token',
            field=models.CharField(default='aaa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trigger',
            name='telegrambot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.Telegrambot'),
        ),
    ]
