# Generated by Django 2.0.1 on 2018-02-12 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegrambot', '0002_remove_trigger_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_bot', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
